In [96]:
import librosa
import numpy as np
import soundfile as sf

In [100]:
step=1
'./vsCorpus/'+''+str(step)

'./vsCorpus/1'

In [109]:
audio0, samplerate = sf.read('./vsCorpus/pred_mix.wav', dtype='float32')
#audio0 = librosa.resample(audio0.T, samplerate, 16000)
#audio0 = audio0.reshape(-1, 1)
audio0.shape

(97536,)

In [103]:
a = 16000
sf.write('./vsCorpus/1.wav',audio0,a)

In [1]:
import numpy as np

In [107]:
a = np.arange(10)
np.pad(a,[2,2],mode='constant')

array([0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0])

In [108]:
np.roll(a, 4)

array([6, 7, 8, 9, 0, 1, 2, 3, 4, 5])

In [78]:
np.random.randint(0,4)

1

In [95]:
np.random.randn(100)*(1e-5)

array([  7.12452952e-06,  -3.72932229e-06,  -5.76996698e-06,
        -2.56756980e-05,  -2.00329659e-05,  -2.01120005e-06,
        -7.74620794e-06,  -1.39272758e-05,  -2.38788954e-06,
        -8.90645896e-06,  -9.86971720e-07,   1.77613341e-06,
        -1.52536456e-05,   2.92064204e-06,   1.26218007e-05,
        -2.65869606e-06,   2.55479959e-05,   2.04345762e-06,
         1.56484697e-05,  -1.10356561e-05,  -1.93829074e-05,
         1.64907531e-05,   1.45029469e-05,   5.38349860e-06,
         8.13763287e-06,  -4.84601258e-06,  -8.63483935e-06,
         4.96669838e-06,  -2.88646702e-06,  -1.98232893e-05,
        -9.68153205e-06,   1.80012437e-05,  -1.07143197e-05,
         2.22307468e-06,   1.84173448e-05,   8.36766453e-07,
        -4.05871100e-06,  -1.16907051e-05,  -1.07261167e-05,
        -6.89975019e-06,   6.13963657e-06,   4.64804354e-06,
        -1.94973588e-05,  -3.51478955e-06,   8.94159622e-06,
         6.85158332e-07,  -4.52118153e-06,  -1.29460293e-05,
         2.46298838e-05,

In [80]:
import librosa
import numpy as np
import soundfile as sf

In [90]:
filename = ['./vsCorpus/pred_mix.wav','./vsCorpus/origin_vocal.wav']
audio0, samplerate = sf.read(filename[0], dtype='float32')
audio0 = librosa.resample(audio0.T, samplerate, 16000)
audio0 = audio0.reshape(-1, 1)
audio0.shape

(190500, 1)

In [88]:
audio0[10100:10200]

array([[  2.37370245e-02],
       [  6.97137564e-02],
       [  1.35795996e-01],
       [  1.45683378e-01],
       [  1.23145200e-01],
       [  1.24482378e-01],
       [  1.29988745e-01],
       [  9.37527791e-02],
       [  4.52679656e-02],
       [  4.35558669e-02],
       [  6.80296719e-02],
       [  5.32581657e-02],
       [  7.91466050e-03],
       [  2.35935659e-04],
       [  3.64894308e-02],
       [  5.20735160e-02],
       [  2.43647341e-02],
       [ -1.35247328e-03],
       [ -8.07452481e-03],
       [ -3.19585241e-02],
       [ -6.89915419e-02],
       [ -5.47923706e-02],
       [  2.21106876e-02],
       [  7.74778724e-02],
       [  5.63833117e-02],
       [  1.95676815e-02],
       [  3.75835747e-02],
       [  7.09940121e-02],
       [  4.09951545e-02],
       [ -3.21916379e-02],
       [ -5.63867167e-02],
       [ -8.86394829e-03],
       [  3.84842008e-02],
       [  3.20383795e-02],
       [ -2.60234764e-03],
       [ -2.21588109e-02],
       [ -2.45696232e-02],
 