In [2]:
import tensorflow as tf
import numpy as np
tf.logging.set_verbosity(tf.logging.INFO)

In [11]:
w = tf.Variable([1.0,2.0,3.0,4.0],trainable=True)
x = tf.Variable([1.0,2.0,3.0,4.0],trainable=True)
opt = tf.train.AdamOptimizer()
l1re=tf.contrib.layers.l1_regularizer(scale=0.005)
with tf.Session() as sess:
    sess.run(x.initializer)
    weights = tf.trainable_variables()
    print(sess.run(x[1:10000]))
    l1loss = tf.contrib.layers.apply_regularization(l1re,weights)
    print(sess.run(l1loss))
    print(x.eval())
    

[ 2.  3.  4.]


TypeError: Expected int32, got 0.005 of type 'float' instead.

In [12]:
y_true = tf.convert_to_tensor(np.array([[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]]))
y_hat = tf.convert_to_tensor(np.array([[0.5, 1.5, 0.1],[2.2, 1.3, 1.7]]))
y_hat_softmax = tf.nn.softmax(y_hat)
y_cross = y_true * tf.log(y_hat_softmax)
result = - tf.reduce_sum(y_cross, 1)
result_tf = tf.nn.softmax_cross_entropy_with_logits_v2(labels = y_true, logits = y_hat)
with tf.Session() as sess:
    sess.run(result)
    sess.run(result_tf)
    print('y_hat_softmax:\n{0}\n'.format(y_hat_softmax.eval()))
    print('y_true: \n{0}\n'.format(y_true.eval()))
    print('y_cross: \n{0}\n'.format(y_cross.eval()))
    print('result: \n{0}\n'.format(result.eval()))
    print('result_tf: \n{0}'.format(result_tf.eval()))

y_hat_softmax:
[[ 0.227863    0.61939586  0.15274114]
 [ 0.49674623  0.20196195  0.30129182]]

y_true: 
[[ 0.  1.  0.]
 [ 0.  0.  1.]]

y_cross: 
[[-0.         -0.4790107  -0.        ]
 [-0.         -0.         -1.19967598]]

result: 
[ 0.4790107   1.19967598]

result_tf: 
[ 0.4790107   1.19967598]


In [6]:
x = tf.Variable([1.0,0.0])
with tf.Session() as sess:
    sess.run(x.initializer)
    y = tf.nn.softmax(x)
    sess.run(y)
    y = tf.Print(y,[y])
    sess.run(y)
    print(y.eval())

[ 0.7310586   0.26894143]


In [11]:
x = tf.Variable([[1.0,0.0],[0.1,0.5]])
y = tf.Variable([0,1])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits=x,labels=y)
    sess.run(loss)
    print(loss.eval())


[ 1.31326163  0.51301527]


In [9]:
import tensorflow as tf
sess = tf.InteractiveSession()
#sess = tf.Session()
a = tf.Variable(5.0)
b = tf.Variable(6.0)
sess.run(tf.global_variables_initializer())
print(sess.run(tf.report_uninitialized_variables()))
c = a * b
# We can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()

[]
30.0


/home/coder.chenshicheng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [2]:
'''from scipy.io import wavfile
rate,data = wavfile.read('./vocalSeparation/origin_mix.wav')
rate1,data1 = wavfile.read('./vocalSeparation/origin_vocal.wav')
rate2,data2 = wavfile.read('./vocalSeparation/pred_mix.wav')
rate3,data3 = wavfile.read('./vocalSeparation/pred_vocal.wav')
print(data.shape,data1.shape,data2.shape,data3.shape)'''
#scipy.io.wavfile.write('./vocalSeparation/morigin_mix.wav',rate,data)

(1930834,) (1930834,) (97536,) (97536,)


In [65]:
import tensorflow as tf
with tf.name_scope("Scope_A"):
    a = tf.add(1, 2, name="A_add")
    b = tf.multiply(a, 3, name="A_mul")
with tf.name_scope("Scope_B"):
    c = tf.add(4, 5, name="B_add")
    d = tf.multiply(c, 6, name="B_mul")
e = tf.add(b, d, name="output")
writer = tf.summary.FileWriter('./name_scope', graph=tf.get_default_graph())
writer.close()

In [63]:
import tensorflow as tf
import numpy as np
with tf.Session() as sess:
    tf.logging.set_verbosity(tf.logging.INFO)
    x = tf.Variable([[1., 2., 3.],[4., 5., 6.]])
    rx = tf.reshape(x, [1, 2, 3, 1])
    valid_pad = tf.nn.max_pool(rx, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
    same_pad = tf.nn.max_pool(rx, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME')
    psame_pad = tf.Print(same_pad,[same_pad],'where are u')
    print(sess.run(x.initializer))
    print(sess.run(psame_pad))
    print(psame_pad.eval())

None
[[[[ 5.]
   [ 6.]]]]
[[[[ 5.]
   [ 6.]]]]


In [57]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()
tf.logging.set_verbosity(tf.logging.INFO)
#x = tf.Variable([[1., 2., 3.],[4., 5., 6.]])
x = tf.placeholder(dtype=tf.float32,shape=[2,3])
rx = tf.reshape(x, [1, 2, 3, 1])
valid_pad = tf.nn.max_pool(rx, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad = tf.nn.max_pool(rx, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME')

#print(valid_pad)
psame_pad = tf.Print(same_pad,[same_pad],'where are u')
print(sess.run(psame_pad,feed_dict=
               {x:np.array([[1., 2., 3.],[4., 5., 6.]],dtype=np.float32)}))
sess.close()

[[[[ 5.]
   [ 6.]]]]


/home/coder.chenshicheng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [67]:
'''import tensorflow as tf
import numpy as np
x = tf.placeholder(dtype=tf.float32,shape=None)
result=tf.nn.conv1d(x,np.zeros((2,3,4),dtype=np.float32),stride=1, padding='VALID')
sess = tf.InteractiveSession()
print(sess.run(result,feed_dict={x:np.zeros((1,10,3),dtype=np.float32)}))'''

"import tensorflow as tf\nimport numpy as np\nx = tf.placeholder(dtype=tf.float32,shape=None)\nresult=tf.nn.conv1d(x,np.zeros((2,3,4),dtype=np.float32),stride=1, padding='VALID')\nsess = tf.InteractiveSession()\nprint(sess.run(result,feed_dict={x:np.zeros((1,10,3),dtype=np.float32)}))"

In [20]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()
q = tf.PaddingFIFOQueue(capacity=10, dtypes=[tf.int32, tf.int32], shapes=[[], [None]])
sample0 = tf.placeholder(dtype=tf.int32, shape=None)
sample1 = tf.placeholder(dtype=tf.int32, shape=None)
sample2 = tf.placeholder(dtype=tf.int32, shape=None)
#eq1 = q.enqueue([1, [1]])
eq1 = q.enqueue([sample0, sample1])
eq2 = q.enqueue([2,[2,3]])
eq3 = q.enqueue([3, [4,5,6]])
dq = q.dequeue()
print(sess.run(eq1,feed_dict={sample0:1,sample1:[1]}),
      sess.run(eq2),sess.run(eq3))
print(sess.run(dq) ,sess.run(dq) ,sess.run(dq))

None None None
[1, array([1], dtype=int32)] [2, array([2, 3], dtype=int32)] [3, array([4, 5, 6], dtype=int32)]


/home/coder.chenshicheng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
