In [1]:
import numpy as np

In [4]:
np.concatenate([np.zeros((2,5)),np.zeros((2,5)),np.zeros((2,5))],axis=1).shape

(2, 15)

In [4]:
np.concatenate([np.zeros(5),np.zeros(5),np.zeros(5)])

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.])

In [7]:
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
import numpy as np
import torch.utils.data as utils
import librosa
import soundfile as sf
import time
import os

In [31]:
a = np.arange(3).reshape(1,1,-1).astype(np.float32)

In [33]:
con1 = nn.Conv1d(in_channels=1,out_channels=1,kernel_size=3,dilation=1,padding=1)

In [34]:
con1(torch.tensor(a))

tensor([[[ 0.4433,  0.6411, -0.1987]]])

In [ ]:
con2 = nn.Conv1d(in_channels=1,out_channels=1,kernel_size=3,dilation=2,padding=2)

In [35]:
con1(torch.tensor(a))

tensor([[[ 0.4433,  0.6411, -0.1987]]])

In [37]:
torch.tensor(a).narrow(2,0,3)

tensor([[[ 0.,  1.,  2.]]])